### PR TITLE
Feature 9/get available book headers

### PR DESCRIPTION
**Pull request by PhotoNomad0**
Please review Epitelete.bookHeaders() to make sure it meets requirements.  Added unit test.

### CODE REVIEW

**Comment by mvahowe** [comment]
@PhotoNomad0 Thanks! I think you want to return `bookHeaders` not `bookCodes`. The idea is that the editor gets the names of the document to use in a menu etc, as well as the 3-letter code.

If you like you could have a method to give you just the bookCodes too. I guess that would save someone an `Object.keys()`.

**Comment by PhotoNomad0** [comment]
@mvahowe 
This is what I saw as requirements: `Then I'd map over the array-heavy result to end up with an object with bookCode as the keys and with the other headers as a normal key/value object as the value.`

I am returning an object with bookCode as the keys and the value being an object that contains the headers as key/values.

Am I misunderstanding something?

**Comment by PhotoNomad0** [comment]
Here is an example of what is being returned (in JSON):
```
{
  "1CH": {
    "id": "1CH World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "1 Chronicles",
    "toc": "The First Book of Chronicles",
    "toc2": "1 Chronicles",
    "toc3": "1 Chronicles"
  },
  "1CO": {
    "id": "1CO 46-1CO-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "1 Corinthians",
    "toc": "Paul’s First Letter to the Corinthians",
    "toc2": "1 Corinthians",
    "toc3": "1 Corinthians"
  },
  "1ES": {
    "id": "1ES - 1 Esdras",
    "h": "1 Esdras",
    "toc": "1 Esdras",
    "toc2": "1 Esdras",
    "toc3": "1Es"
  },
  "1JN": {
    "id": "1JN 62-1JN-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "1 John",
    "toc": "John’s First Letter",
    "toc2": "1 John",
    "toc3": "1 John"
  },
  "1KI": {
    "id": "1KI World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "1 Kings",
    "toc": "The First Book of Kings",
    "toc2": "1 Kings",
    "toc3": "1 Kings"
  },
  "1MA": {
    "id": "1MA",
    "h": "1 Maccabees",
    "toc": "The First Book of the Maccabees",
    "toc2": "1 Maccabees",
    "toc3": "1Ma"
  },
  "1PE": {
    "id": "1PE 60-1PE-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "1 Peter",
    "toc": "Peter’s First Letter",
    "toc2": "1 Peter",
    "toc3": "1 Peter"
  },
  "1SA": {
    "id": "1SA World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "1 Samuel",
    "toc": "The First Book of Samuel",
    "toc2": "1 Samuel",
    "toc3": "1 Samuel"
  },
  "1TH": {
    "id": "1TH 52-1TH-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "1 Thessalonians",
    "toc": "Paul’s First Letter to the Thessalonians",
    "toc2": "1 Thessalonians",
    "toc3": "1 Thessalonians"
  },
  "1TI": {
    "id": "1TI 54-1TI-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "1 Timothy",
    "toc": "Paul’s First Letter to Timothy",
    "toc2": "1 Timothy",
    "toc3": "1 Timothy"
  },
  "2CH": {
    "id": "2CH World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "2 Chronicles",
    "toc": "The Second Book of Chronicles",
    "toc2": "2 Chronicles",
    "toc3": "2 Chronicles"
  },
  "2CO": {
    "id": "2CO 47-2CO-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "2 Corinthians",
    "toc": "Paul’s Second Letter to the Corinthians",
    "toc2": "2 Corinthians",
    "toc3": "2 Corinthians"
  },
  "2ES": {
    "id": "2ES - 2 Esdras",
    "h": "2 Esdras",
    "toc": "2 Esdras",
    "toc2": "2 Esdras",
    "toc3": "2Es"
  },
  "2JN": {
    "id": "2JN 63-2JN-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "2 John",
    "toc": "John’s Second Letter",
    "toc2": "2 John",
    "toc3": "2 John"
  },
  "2KI": {
    "id": "2KI World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "2 Kings",
    "toc": "The Second Book of Kings",
    "toc2": "2 Kings",
    "toc3": "2 Kings"
  },
  "2MA": {
    "id": "2MA",
    "h": "2 Maccabees",
    "toc": "The Second Book of the Maccabees",
    "toc2": "2 Maccabees",
    "toc3": "2Ma"
  },
  "2PE": {
    "id": "2PE 61-2PE-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "2 Peter",
    "toc": "Peter’s Second Letter",
    "toc2": "2 Peter",
    "toc3": "2 Peter"
  },
  "2SA": {
    "id": "2SA World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "2 Samuel",
    "toc": "The Second Book of Samuel",
    "toc2": "2 Samuel",
    "toc3": "2 Samuel"
  },
  "2TH": {
    "id": "2TH 53-2TH-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "2 Thessalonians",
    "toc": "Paul’s Second Letter to the Thessalonians",
    "toc2": "2 Thessalonians",
    "toc3": "2 Thessalonians"
  },
  "2TI": {
    "id": "2TI 55-2TI-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "2 Timothy",
    "toc": "Paul’s Second Letter to Timothy",
    "toc2": "2 Timothy",
    "toc3": "2 Timothy"
  },
  "3JN": {
    "id": "3JN 64-3JN-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "3 John",
    "toc": "John’s Third Letter",
    "toc2": "3 John",
    "toc3": "3 John"
  },
  "3MA": {
    "id": "3MA",
    "h": "3 Maccabees",
    "toc": "The Third Book of the Maccabees",
    "toc2": "3 Maccabees",
    "toc3": "3Ma"
  },
  "4MA": {
    "id": "4MA",
    "h": "4 Maccabees",
    "toc": "The Fourth Book of the Maccabees",
    "toc2": "4 Maccabees",
    "toc3": "4Ma"
  },
  "ACT": {
    "id": "ACT 44-ACT-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Acts",
    "toc": "The Acts of the Apostles",
    "toc2": "Acts",
    "toc3": "Acts"
  },
  "AMO": {
    "id": "AMO 30-AMO-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Amos",
    "toc": "The Book of Amos",
    "toc2": "Amos",
    "toc3": "Amos"
  },
  "BAR": {
    "id": "BAR - Baruch",
    "h": "Baruch",
    "toc": "Baruch",
    "toc2": "Baruch",
    "toc3": "Baruch"
  },
  "COL": {
    "id": "COL 51-COL-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Colossians",
    "toc": "Paul’s Letter to the Colossians",
    "toc2": "Colossians",
    "toc3": "Colossians"
  },
  "DAG": {
    "id": "DAG World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Daniel (Greek)",
    "toc": "The Book of Daniel with Greek Portions",
    "toc2": "Daniel (Greek)",
    "toc3": "DAG"
  },
  "DAN": {
    "id": "DAN 27-DAN-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Daniel",
    "toc": "The Book of Daniel",
    "toc2": "Daniel",
    "toc3": "Daniel"
  },
  "DEU": {
    "id": "DEU 1World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Deuteronomy",
    "toc": "The Fifth Book of Moses, Commonly Called Deuteronomy",
    "toc2": "Deuteronomy",
    "toc3": "Deuteronomy"
  },
  "ECC": {
    "id": "ECC World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Ecclesiastes",
    "toc": "Ecclesiates or, The Preacher",
    "toc2": "Ecclesiastes",
    "toc3": "Ecclesiastes"
  },
  "EPH": {
    "id": "EPH 49-EPH-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Ephesians",
    "toc": "Paul’s Letter to the Ephesians",
    "toc2": "Ephesians",
    "toc3": "Ephesians"
  },
  "ESG": {
    "id": "ESG",
    "h": "Esther (Greek)",
    "toc": "Esther (Greek)",
    "toc2": "Esther (Greek)",
    "toc3": "ESG"
  },
  "EST": {
    "id": "EST World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Esther",
    "toc": "The Book of Esther",
    "toc2": "Esther",
    "toc3": "Esther"
  },
  "EXO": {
    "id": "EXO World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Exodus",
    "toc": "The Second Book of Mosis, Commonly Called Exodus",
    "toc2": "Exodus",
    "toc3": "Exodus"
  },
  "EZK": {
    "id": "EZK 6-EZK-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Ezekiel",
    "toc": "The Book of Ezekiel",
    "toc2": "Ezekiel",
    "toc3": "Ezekiel"
  },
  "EZR": {
    "id": "EZR World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Ezra",
    "toc": "The Book of Ezra",
    "toc2": "Ezra",
    "toc3": "Ezra"
  },
  "GAL": {
    "id": "GAL 48-GAL-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Galatians",
    "toc": "Paul’s Letter to the Galatians",
    "toc2": "Galatians",
    "toc3": "Galatians"
  },
  "GEN": {
    "id": "GEN World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Genesis",
    "toc": "The First Book of Moses, Commonly Called Genesis",
    "toc2": "Genesis",
    "toc3": "Genesis"
  },
  "HAB": {
    "id": "HAB 35-HAB-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Habakkuk",
    "toc": "The Book of Habakkuk",
    "toc2": "Habakkuk",
    "toc3": "Habakkuk"
  },
  "HAG": {
    "id": "HAG 7-HAG-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Haggai",
    "toc": "The Book of Haggai",
    "toc2": "Haggai",
    "toc3": "Haggai"
  },
  "HEB": {
    "id": "HEB 58-HEB-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Hebrews",
    "toc": "The Letter to the Hebrews",
    "toc2": "Hebrews",
    "toc3": "Hebrews"
  },
  "HOS": {
    "id": "HOS 28-HOS-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Hosea",
    "toc": "The Book of Hosea",
    "toc2": "Hosea",
    "toc3": "Hosea"
  },
  "ISA": {
    "id": "ISA 23-ISA-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Isaiah",
    "toc": "The Book of Isaiah",
    "toc2": "Isaiah",
    "toc3": "Isaiah"
  },
  "JAS": {
    "id": "JAS 59-JAS-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "James",
    "toc": "The Letter from James",
    "toc2": "James",
    "toc3": "James"
  },
  "JDG": {
    "id": "JDG World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Judges",
    "toc": "The Book of Judges",
    "toc2": "Judges",
    "toc3": "Judges"
  },
  "JDT": {
    "id": "JDT Judith",
    "h": "Judith",
    "toc": "Judith",
    "toc2": "Judith",
    "toc3": "Judith"
  },
  "JER": {
    "id": "JER 24-JER-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Jeremiah",
    "toc": "The Book of Jeremiah",
    "toc2": "Jeremiah",
    "toc3": "Jeremiah"
  },
  "JHN": {
    "id": "JHN 43-JHN-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "John",
    "toc": "The Good News According to John",
    "toc2": "John",
    "toc3": "John"
  },
  "JOB": {
    "id": "JOB World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Job",
    "toc": "The Book of Job",
    "toc2": "Job",
    "toc3": "Job"
  },
  "JOL": {
    "id": "JOL 29-JOL-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Joel",
    "toc": "The Book of Joel",
    "toc2": "Joel",
    "toc3": "Joel"
  },
  "JON": {
    "id": "JON 2-JON-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Jonah",
    "toc": "The Book of Jonah",
    "toc2": "Jonah",
    "toc3": "Jonah"
  },
  "JOS": {
    "id": "JOS World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Joshua",
    "toc": "The Book of Joshua",
    "toc2": "Joshua",
    "toc3": "Joshua"
  },
  "JUD": {
    "id": "JUD 65-JUD-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Jude",
    "toc": "The Letter from Jude",
    "toc2": "Jude",
    "toc3": "Jude"
  },
  "LAM": {
    "id": "LAM 25-LAM-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Lamentations",
    "toc": "The Lamentations of Jeremiah",
    "toc2": "Lamentations",
    "toc3": "Lamentations"
  },
  "LEV": {
    "id": "LEV World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Leviticus",
    "toc": "The Third Book of Mosis, Commonly Called Leviticus",
    "toc2": "Leviticus",
    "toc3": "Leviticus"
  },
  "LUK": {
    "id": "LUK 42-LUK-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Luke",
    "toc": "The Good News According to Luke",
    "toc2": "Luke",
    "toc3": "Luke"
  },
  "MAL": {
    "id": "MAL 39-MAL-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Malachi",
    "toc": "The Book of Malachi",
    "toc2": "Malachi",
    "toc3": "Malachi"
  },
  "MAN": {
    "id": "MAN",
    "h": "Prayer of Manasses",
    "toc": "The Prayer of Manasses King of Judah when He was Held Captive in Babylon",
    "toc2": "Prayer of Manasses",
    "toc3": "Man"
  },
  "MAT": {
    "id": "MAT 40-MAT-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Matthew",
    "toc": "The Good News According to Matthew",
    "toc2": "Matthew",
    "toc3": "Matthew"
  },
  "MIC": {
    "id": "MIC 33-MIC-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Micah",
    "toc": "The Book of Micah",
    "toc2": "Micah",
    "toc3": "Micah"
  },
  "MRK": {
    "id": "MRK 41-MRK-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Mark",
    "toc": "The Good News According to Mark",
    "toc2": "Mark",
    "toc3": "Mark"
  },
  "NAM": {
    "id": "NAM 34-NAM-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Nahum",
    "toc": "The Book of Nahum",
    "toc2": "Nahum",
    "toc3": "Nahum"
  },
  "NEH": {
    "id": "NEH World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Nehemiah",
    "toc": "The Book of Nehemiah",
    "toc2": "Nehemiah",
    "toc3": "Nehemiah"
  },
  "NUM": {
    "id": "NUM World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Numbers",
    "toc": "The Fourth Book of Moses, Commonly Called Numbers",
    "toc2": "Numbers",
    "toc3": "Numbers"
  },
  "OBA": {
    "id": "OBA 31-OBA-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Obadiah",
    "toc": "The Book of Obadiah",
    "toc2": "Obadiah",
    "toc3": "Obadiah"
  },
  "PHM": {
    "id": "PHM 57-PHM-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Philemon",
    "toc": "Paul’s Letter to Philemon",
    "toc2": "Philemon",
    "toc3": "Philemon"
  },
  "PHP": {
    "id": "PHP 50-PHP-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Philippians",
    "toc": "Paul’s Letter to the Philippians",
    "toc2": "Philippians",
    "toc3": "Philippians"
  },
  "PRO": {
    "id": "PRO World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Proverbs",
    "toc": "The Proverbs",
    "toc2": "Proverbs",
    "toc3": "Proverbs"
  },
  "PS2": {
    "id": "PS2",
    "h": "Psalm 151",
    "toc": "Psalm 151",
    "toc2": "Psalm 151",
    "toc3": "Ps151"
  },
  "PSA": {
    "id": "PSA World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Psalms",
    "toc": "The Psalms",
    "toc2": "Psalms",
    "toc3": "Psalm",
    "cl": "Psalm"
  },
  "REV": {
    "id": "REV 66-REV-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Revelation",
    "toc": "The Revelation to John",
    "toc2": "Revelation",
    "toc3": "Revelation"
  },
  "ROM": {
    "id": "ROM 45-ROM-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Romans",
    "toc": "Paul’s Letter to the Romans",
    "toc2": "Romans",
    "toc3": "Romans"
  },
  "RUT": {
    "id": "RUT World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Ruth",
    "toc": "The Book of Ruth",
    "toc2": "Ruth",
    "toc3": "Ruth"
  },
  "SIR": {
    "id": "SIR Ecclesiasticus",
    "h": "Sirach",
    "toc": "The Wisdom of Jesus the Son of Sirach, or Ecclesiasticus",
    "toc2": "Sirach",
    "toc3": "Sirach"
  },
  "SNG": {
    "id": "SNG World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Song of Solomon",
    "toc": "The Song of Solomon",
    "toc2": "Song of Solomon",
    "toc3": "Song of Solomon"
  },
  "TIT": {
    "id": "TIT 56-TIT-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Titus",
    "toc": "Paul’s Letter to Titus",
    "toc2": "Titus",
    "toc3": "Titus"
  },
  "TOB": {
    "id": "TOB - Tobit",
    "h": "Tobit",
    "toc": "Tobit",
    "toc2": "Tobit",
    "toc3": "Tobit"
  },
  "WIS": {
    "id": "WIS - The Wisdom Of Solomon",
    "h": "Wisdom of Solomon",
    "toc": "The Wisdom of Solomon",
    "toc2": "Wisdom of Solomon",
    "toc3": "Wisdom"
  },
  "ZEC": {
    "id": "ZEC 38-ZEC-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Zechariah",
    "toc": "The Book of Zechariah",
    "toc2": "Zechariah",
    "toc3": "Zechariah"
  },
  "ZEP": {
    "id": "ZEP 36-ZEP-web.sfm World English Bible British Edition (WEBBE)",
    "ide": "UTF-8",
    "h": "Zephaniah",
    "toc": "The Book of Zephaniah",
    "toc2": "Zephaniah",
    "toc3": "Zephaniah"
  }
}
```

**Comment by mvahowe** [comment]
@PhotoNomad0 This looks right to me. I'm not sure how useful id and ide are, but I think it makes sense to return all the headers, because the data size is not huge, and because 'Proskomma document headers' are a known thing that we therefore don't need to specify here.

**Pull request merged**
